import {configured,accessToken,signIn,acceptSignInLink,signOut} from '../shared/connection.js?v=1e601bdcde1c';
import {publishedPoems,loadStudio,saveCollection} from '../shared/poetry-store.js?v=1e601bdcde1c';
import {readingOrder} from './order.js?v=1e601bdcde1c';
let backendReady=false,active;
const $=id=>document.getElementById(id),motion=matchMedia('(prefers-reduced-motion: reduce)');
const menu=$('studio-menu');$('studio-toggle').onclick=()=>{menu.hidden=!menu.hidden;$('studio-toggle').setAttribute('aria-expanded',String(!menu.hidden));};
function route(){const view=['write','review'].includes(location.hash.slice(1))?location.hash.slice(1):'read';for(const name of ['read','write','review'])$(name+'-view').hidden=name!==view;$('section-name').textContent=view.toUpperCase();menu.hidden=true;$('studio-toggle').setAttribute('aria-expanded','false');$('studio-auth').hidden=view==='read'||backendReady||!configured; if(view==='write'&&backendReady)openDraft(active);if(view==='review'&&backendReady)renderReview();for(const el of document.querySelectorAll('#write-view input,#write-view textarea,#write-view button,#review-view input,#review-view select,#review-view button'))el.disabled=!backendReady;}
addEventListener('hashchange',route);addEventListener('keydown',e=>{if(e.key==='Escape'){menu.hidden=true;$('studio-toggle').setAttribute('aria-expanded','false');}});
let index=0,count=0;const pages=$('pages');
function controls(){index=Math.round(pages.scrollLeft/Math.max(1,pages.clientWidth));$('previous').disabled=index<=0;$('next').disabled=index>=count-1;$('position').textContent=count?`${index+1} / ${count}`:'';}
function turn(direction){const target=Math.max(0,Math.min(count-1,index+direction));if(target===index)return;pages.scrollTo({left:target*pages.clientWidth,behavior:motion.matches?'instant':'smooth'});}
$('previous').onclick=()=>turn(-1);$('next').onclick=()=>turn(1);pages.addEventListener('scroll',controls,{passive:true});pages.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();turn(e.key==='ArrowRight'?1:-1);}});
let resizeTimer;addEventListener('resize',()=>{const current=index;clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{pages.scrollTo({left:current*pages.clientWidth,behavior:'instant'});controls();},100);});
try{const data=await publishedPoems();const poems=data.filter(p=>typeof p.id==='string'&&typeof p.body==='string'&&p.published===true);let saved;try{saved=JSON.parse(sessionStorage.getItem('poetry-order'));}catch{}const order=readingOrder(poems,saved);try{sessionStorage.setItem('poetry-order',JSON.stringify(order));}catch{}count=order.length;for(const id of order){const poem=poems.find(p=>p.id===id),page=document.createElement('article'),content=document.createElement('div'),title=document.createElement('h1'),body=document.createElement('pre');page.className='page';content.className='page-content';title.textContent=poem.title||'Untitled';body.className='poem';body.textContent=poem.body;content.append(title,body);if(poem.author){const author=document.createElement('p');author.className='byline';author.textContent=poem.author;content.append(author);}page.append(content);pages.append(page);}if(count){pages.hidden=false;$('reader-footer').hidden=false;}if(!count){pages.hidden=true;$('empty').hidden=false;$('reader-footer').hidden=true;}controls();}catch{pages.hidden=true;$('empty').hidden=false;$('reader-footer').hidden=true;$('empty-message').textContent='The collection couldn’t be loaded. Please try again later.';}
dispatchEvent(new Event('site-ready'));
const key='verse-web-drafts-v1';let drafts=[];try{drafts=configured?[]:JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(drafts))drafts=[];}catch{}let revisions={},submissions=[],saveQueue=Promise.resolve();
try{await acceptSignInLink();const studio=await loadStudio();drafts=studio.drafts;submissions=studio.submissions;revisions=studio.revisions;backendReady=true;}catch(error){$('save-state').textContent=configured?error.message:'Studio unavailable — export a copy';}
active=drafts[0]?.id;
function persist(){
 if(!configured)try{localStorage.setItem(key,JSON.stringify(drafts));}catch{}
 if(!backendReady){$('save-state').textContent='Studio offline — export a copy';return;}
 const snapshot=JSON.parse(JSON.stringify(drafts));$('save-state').textContent='Saving…';
 return saveQueue=saveQueue.catch(()=>{}).then(async()=>{revisions.drafts=await saveCollection('drafts',snapshot,revisions.drafts);$('save-state').textContent=configured?'Saved to your online studio':'Saved on this Mac';return true;}).catch(error=>{$('save-state').textContent=error.message;return false;});
}
function list(){const root=$('draft-list');root.replaceChildren();for(const draft of drafts){const button=document.createElement('button');button.textContent=draft.title||'Untitled';button.setAttribute('aria-current',String(draft.id===active));button.onclick=()=>openDraft(draft.id);root.append(button);}}
function openDraft(id){if(!drafts.length){drafts.push({id:crypto.randomUUID(),title:'',body:'',versions:[]});persist();}const draft=drafts.find(d=>d.id===id)||drafts[0];active=draft.id;$('draft-title').value=draft.title;$('draft-body').value=draft.body;list();history();}
function save(){const draft=drafts.find(d=>d.id===active);if(!draft)return;draft.title=$('draft-title').value;draft.body=$('draft-body').value;persist();list();}
$('draft-title').addEventListener('input',save);$('draft-body').addEventListener('input',save);
$('new-draft').onclick=()=>{const draft={id:crypto.randomUUID(),title:'',body:'',versions:[]};drafts.unshift(draft);persist();openDraft(draft.id);$('draft-body').focus();};
$('keep-draft').onclick=()=>{save();const draft=drafts.find(d=>d.id===active);draft.versions.unshift({date:new Date().toISOString(),title:draft.title,body:draft.body});persist();history();};
$('show-history').onclick=()=>{$('history').hidden=!$('history').hidden;$('show-history').setAttribute('aria-expanded',String(!$('history').hidden));};
function history(){const root=$('history');root.replaceChildren();const versions=drafts.find(d=>d.id===active)?.versions||[];if(!versions.length){root.textContent='No saved versions yet.';return;}for(const version of versions){const item=document.createElement('details'),summary=document.createElement('summary'),text=document.createElement('pre');item.className='history-item';summary.textContent=new Date(version.date).toLocaleString();text.textContent=version.title+'\n\n'+version.body;item.append(summary,text);root.append(item);}}
$('export-draft').onclick=()=>{save();const draft=drafts.find(d=>d.id===active),url=URL.createObjectURL(new Blob([draft.title+'\n\n'+draft.body],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=(draft.title||'Untitled').replace(/[^a-z0-9 _-]/gi,'').slice(0,100)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function renderReview(){
 const root=$('publication-list'),select=$('submission-poem');root.replaceChildren();select.replaceChildren();
 if(!drafts.length)root.textContent='Create a poem in Write to get started.';
 for(const draft of drafts){
  const row=document.createElement('div'),title=document.createElement('span'),label=document.createElement('label'),check=document.createElement('input');row.className='publication-row';title.textContent=draft.title||'Untitled';check.type='checkbox';check.checked=draft.published===true;check.disabled=!draft.body.trim()||!backendReady;check.onchange=async()=>{draft.published=check.checked;check.disabled=true;const saved=await persist();$('review-state').textContent=saved?'Publication choice saved. Reload Read to see the updated collection.':'Could not confirm publication. Export your poem, then reload.';check.disabled=false;};label.append(check,document.createTextNode(' Published to site'));row.append(title,label);root.append(row);
  const option=document.createElement('option');option.value=draft.id;option.textContent=draft.title||'Untitled';select.append(option);
 }
 const records=$('submissions');records.replaceChildren();
 if(!submissions.length)records.textContent='No submissions yet.';
 for(const record of submissions){const row=document.createElement('div'),title=document.createElement('strong'),status=document.createElement('select'),response=document.createElement('input'),notes=document.createElement('textarea');row.className='submission-record';title.textContent=(drafts.find(d=>d.id===record.poemId)?.title||'Untitled')+' / '+record.magazine+' / sent '+record.sent;
 for(const value of ['submitted','accepted','rejected','withdrawn']){const option=document.createElement('option');option.value=value;option.textContent=value;status.append(option);}status.value=record.status;status.setAttribute('aria-label','Submission status');response.type='date';response.value=record.response||'';response.setAttribute('aria-label','Response date');notes.value=record.notes||'';notes.placeholder='Notes';notes.setAttribute('aria-label','Submission notes');status.onchange=()=>{record.status=status.value;saveSubmissions();};response.onchange=()=>{record.response=response.value;saveSubmissions();};notes.onchange=()=>{record.notes=notes.value;saveSubmissions();};row.append(title,status,response,notes);records.append(row);}
}
let submissionQueue=Promise.resolve();
function saveSubmissions(){const snapshot=JSON.parse(JSON.stringify(submissions));$('review-state').textContent='Saving…';return submissionQueue=submissionQueue.catch(()=>{}).then(async()=>{revisions.submissions=await saveCollection('submissions',snapshot,revisions.submissions);$('review-state').textContent=configured?'Saved to your online studio':'Saved on this Mac';}).catch(error=>{$('review-state').textContent=error.message;});}
$('submission-form').onsubmit=async event=>{event.preventDefault();if(!backendReady)return;submissions.push({id:crypto.randomUUID(),poemId:$('submission-poem').value,magazine:$('magazine').value.trim(),sent:$('sent').value,response:'',status:'submitted',notes:''});await saveSubmissions();$('magazine').value='';renderReview();};
$('studio-note').textContent=configured?'Your private online workspace. Choose what to publish in Review.':'Drafts are saved on this Mac. Keep versions as you work, then choose what to publish in Review.';
$('studio-login-form').onsubmit=async e=>{e.preventDefault();$('studio-send').disabled=true;try{await signIn($('studio-email').value.trim(),new URL('./',location.href).href);$('studio-login-state').textContent='Open the sign-in email on this device.';}catch(error){$('studio-login-state').textContent=error.message;}finally{$('studio-send').disabled=false;}};
$('studio-sign-out').hidden=!configured||!backendReady;$('studio-sign-out').onclick=()=>{signOut();location.reload();};
route();
