import {configured,listPhotos,publishPhoto,preparedPhoto,accessToken,signIn,acceptSignInLink,signOut} from '../shared/connection.js';
import {DISPLAY_MS,choosePhoto,frameSize} from './gallery.js';
const $=id=>document.getElementById(id);let photos=[],current=0,timer=null,showing=null,generation=0,selected=null,previewUrl=null,uploadId=null;
$('menu-button').onclick=()=>{$('menu').hidden=!$('menu').hidden;$('menu-button').setAttribute('aria-expanded',String(!$('menu').hidden));};
function resize(){if(!showing)return;const size=frameSize(innerWidth,innerHeight,showing.orientation==='portrait',innerWidth<=600?24:32);$('frame').style.width=size.width+'px';$('frame').style.height=size.height+'px';}
function schedule(){clearTimeout(timer);if(!document.hidden&&location.hash!=='#upload')timer=setTimeout(async()=>{try{photos=await listPhotos();}catch{}if(photos.length>1)show(choosePhoto(photos,showing?.id));else if(photos.length===1&&photos[0].id!==showing?.id)show(0);else schedule();},DISPLAY_MS);}
async function show(index){if(!photos.length)return;const token=++generation,item=photos[index],loaded=new Image();loaded.src=item.url;try{await loaded.decode();}catch{if(token===generation){$('empty').textContent='This photograph couldn’t be loaded.';$('empty').hidden=false;}schedule();return;}if(token!==generation)return;current=index;showing=item;$('photo').src=loaded.src;$('photo').alt=item.description||'Photograph';resize();$('frame').hidden=false;$('empty').hidden=true;schedule();}
async function loadGallery(){try{photos=await listPhotos();if(photos.length)await show(choosePhoto(photos,null));else{$('frame').hidden=true;$('empty').hidden=false;$('empty').textContent='No photographs yet.';schedule();}}catch{$('empty').textContent='The gallery couldn’t be loaded. Please try again.';}}
async function route(){const upload=location.hash==='#upload';$('upload').hidden=!upload;$('gallery').hidden=upload;$('menu').hidden=true;$('menu-button').setAttribute('aria-expanded','false');clearTimeout(timer);if(!upload)loadGallery();else await showLogin();}
addEventListener('hashchange',route);addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(timer);else schedule();});
$('file').onchange=async()=>{selected=null;$('upload-form').hidden=true;$('preview').hidden=true;const file=$('file').files[0];if(!file)return;if(file.size>20*1024*1024){$('status').textContent='Choose a photograph smaller than 20 MB.';return;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){$('status').textContent='Choose a JPEG, PNG or WebP photograph.';return;}if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);const img=new Image();img.src=previewUrl;try{await img.decode();}catch{$('status').textContent='This image could not be opened.';return;}selected=file;uploadId=crypto.randomUUID();const portrait=img.naturalHeight>img.naturalWidth,ratio=portrait?2/3:3/2;const size=frameSize(Math.min(innerWidth-56,664),innerHeight*.48,portrait,0);$('preview').src=previewUrl;$('preview').style.width=size.width+'px';$('preview').style.height=size.height+'px';$('preview').hidden=false;$('upload-form').hidden=false;$('status').textContent=`${portrait?'Portrait · 2:3':'Landscape · 3:2'} centered crop preview`;};

async function showLogin(){const loggedIn=!configured||Boolean(await accessToken());$('login').hidden=loggedIn;$('sign-out').hidden=!configured||!loggedIn;$('upload-controls').hidden=!loggedIn;$('storage-note').textContent=configured?'Publish an optimized copy to the gallery. Keep the original in your photo library.':'Local preview: photographs are saved on this Mac. Online publishing is not connected yet.';$('save').textContent=configured?'Publish photo':'Add to local gallery';}
$('login-form').onsubmit=async event=>{event.preventDefault();const button=$('send-code');button.disabled=true;try{await signIn($('email').value.trim());$('login-status').textContent='Check your email and open the sign-in link on this device.';}catch(error){$('login-status').textContent=error.message;}finally{button.disabled=false;}};
$('sign-out').onclick=async()=>{signOut();await showLogin();};
$('upload-form').onsubmit=async event=>{event.preventDefault();if(!selected)return;$('save').disabled=true;$('file').disabled=true;$('status').textContent='Preparing your photo…';try{const file=configured?await preparedPhoto(selected):selected;$('status').textContent=configured?'Publishing…':'Saving on this Mac…';await publishPhoto(file,$('description').value.trim()||selected.name.replace(/\.[^.]+$/,''),uploadId);$('status').textContent=configured?'Published. Your photo is in the rotation.':'Saved on this Mac and added to the rotation.';$('success').hidden=false;$('upload-form').hidden=true;$('file').value='';selected=null;uploadId=null;}catch(error){$('status').textContent=error.message||'Couldn’t save. Please try again.';}finally{$('save').disabled=false;$('file').disabled=false;}};
try{await acceptSignInLink();}catch(error){$('login-status').textContent=error.message;}
await route();
